### ISSUE TITLE
Plugin does not work with Django 1.5.8 because app_label is not available

### ISSUE THREAD

**Issue by nolanlove** [mishbahr/django-modeladmin-reorder#11]
Django Version:	1.5.8
Exception Type:	KeyError
Exception Value:	
'app_label'
Exception Location:	/Users/nolanlove/Documents/development/HEROKU/heroku-pollvault/lib/python2.7/site-packages/admin_reorder/middleware.py in init_config, line 38

**Comment by mishbahr** [comment]
I'll look into this as soon as I can.

**Comment by mishbahr** [comment]
I'm sorry. I don't have project w/ django 1.5  to be able to reproduce this.
