### ISSUE TITLE
No Effect

### ISSUE THREAD

**Issue by gregpinero** [mishbahr/django-modeladmin-reorder#12]
I followed the install steps, and tried a simple:

ADMIN_REORDER = (

    # Rename app
    {'app': 'auth', 'label': 'Authorization'},

)

But nothing changed.  Is it case sensitive?  Or is it that I'm on Django 1.2?

**Comment by mishbahr** [comment]
Have you added the middleware?  I'm sorry but I can't help you with a django version that is so old!

**Comment by gregpinero** [comment]
Yes, I did add the middleware.  Maybe it is something with the age.

**Comment by mishbahr** [comment]
`django v1.2.x` is not available in github .. so I installed locally to investigate.

`django-modeladmin-reorder` uses a middleware to modify context. 

According to docs `.process_template_response()` was added in django 1.3.

See http://django.readthedocs.io/en/1.3.X/topics/http/middleware.html#process-template-response
