### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by gregpinero** [mishbahr/django-modeladmin-reorder#13]
How do you arrange apps on the screen, and items within the apps?  It wasn't clear to me from the documentation.

**Comment by mishbahr** [comment]
Ordering is handled via `ADMIN_REORDER` setting and no drag and drop interface is available. 

Please refer to the [README.rst](https://github.com/mishbahr/django-modeladmin-reorder/blob/master/README.rst) file. Thanks.

**Comment by gregpinero** [comment]
Sorry, my question was confusing.  I was wondering about how to use the ADMIN_REORDER setting.

So the order of app's in that tuple controls how the apps are ordered?

**Comment by mishbahr** [comment]
You are correct.

**Comment by mishbahr** [comment]
I'm closing this as its not really an issue.
