### ISSUE TITLE
How I can add python-social-auth?

### ISSUE THREAD

**Issue by recfunc** [mishbahr/django-modeladmin-reorder#14]
I tried: `'social.apps.django_app.default', 'social', 'social.apps.django.app', 'default'`.
It doesn't work...

**Comment by mishbahr** [comment]
Have you figured this out? Ive been ridiculously busy .. last few weeks. I'll actually have to install `python-social-auth` on a project to figure out how to add it.

This package modifies context using a middleware .. may be you could use `django-debug-toolbar` to have a look at template context for django admin index page?
