### ISSUE TITLE
Compatible with what versions of Django?

### ISSUE THREAD

**Issue by frnhr** [mishbahr/django-modeladmin-reorder#16]
It would be very useful to see what versions of Django was this package tested against.

**Comment by mishbahr** [comment]
This package was written for django 1.6. It was meant to be a small "hack" to make django admin more user friendly (for a small project w/ very limited budget). I haven't had the chance or the budget to go back and add tests or checks to make sure it works w/ some of the latest versions of django.

If you use this package in your project .. please fork this and write some unit tests. Pull requests are welcome!

Many Thanks

Mishbah
