### ISSUE TITLE
KeyError on attribute app["app_label"]

### ISSUE THREAD

**Issue by pinghsien422** [mishbahr/django-modeladmin-reorder#22]
Hi @mishbahr 

I'm using 0.1.3 version of admin_reorder, since the project I'm handling have legacy transaction code that requires django 1.5.1. For some reason I can't get this to run because of KeyError in middleware.py:

         # Flatten all models from apps
         self.models_list = []
         for app in app_list:
             for model in app['models']:
                 model['model_name'] = self.get_model_name(
                     app['app_label'], model['object_name'])
                 self.models_list.append(model)

From the above snipet, I not only missing app['app_label'], I am also missing model['object_name'].

This is the content I have for app:

{'app_url': '/admin/auth/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'add_url': '/admin/auth/group/add/', 'admin_url': '/admin/auth/group/', 'name': <django.utils.functional.__proxy__ object at 0x7f70f35f9c50>}, {'perms': {'add': True, 'change': True, 'delete': True}, 'add_url': '/admin/auth/user/add/', 'admin_url': '/admin/auth/user/', 'name': <django.utils.functional.__proxy__ object at 0x7f70f35e0710>}], 'has_module_perms': True, 'name': u'Auth'}

Is this because I'm using an old django version, or am I missing something?

Thanks,
John

**Comment by mishbahr** [comment]
Looking at the source code https://github.com/django/django/blob/stable/1.5.x/django/contrib/admin/sites.py#L429

The context passed to view does not include `app_label`

Comparing that to django v1.6.x

https://github.com/django/django/blob/stable/1.6.x/django/contrib/admin/sites.py#L428

**Comment by pinghsien422** [comment]
I see, here I thought admin_reorder v0.1.3 supports django 1.5.x?

**Comment by mishbahr** [comment]
I'm sorry, I don't think it evar supported v1.5.x, I wrote this for a client project using django v1.6

**Comment by pinghsien422** [comment]
Ah ok, it's still supported on the most current django version? (1.11)

**Comment by mishbahr** [comment]
I haven't used this package for a while in my projects. As generally, we don't  expose Django admin interface to clients. Please try it, and let me know if you have any issues. Thanks

**Comment by mishbahr** [comment]
No updates from OP.  Closing this for now.
