### ISSUE TITLE
Re ordering not happening

### ISSUE THREAD

**Issue by Sahana312** [mishbahr/django-modeladmin-reorder#24]
I installed the `django-modeladmin-reorder` using `pip`. Included `admin_reorder` in my `INSTALLED_APPS` and also `'admin_reorder.middleware.ModelAdminReorder`' to my `MIDDLEWARE_CLASSES`.  Below is my `ADMIN_REORDER` section 
```python
ADMIN_REORDER = (
    # Other
    {
        'app': 'auth',
        'label': 'Authentication and Authorization',
        'models': ('auth.Group', 'auth.User', )
    },
    {
        'app': 'other',
        'label': 'Payments',
        'models': ('other.Currency', 'other.ExchangeRate', 'other.PaymentMethod', )
    }, 
    {
        'app': 'other',
        'label': 'POS Management',
        'models': ('other.DeviceInfo', 'other.Environment', )
    }, 
    {
        'app': 'other',
        'label': 'Reason Codes',
        'models': ('other.ReasonCodeCategory', 'other.ReasonCode')
    }

)
```
This doesnot give the desired output. Where am I going wrong ?

**Comment by mishbahr** [comment]
What do you mean by "does not give the desired output"? Can you provide a screenshot? Have you checked your app name i.e is is called `other`?

**Comment by Sahana312** [comment]
![other](https://user-images.githubusercontent.com/19899785/27906037-8c7e8ac4-625f-11e7-963e-0947f96ed93a.png)


Have attached the screenshot. Yes I am sure about the app name. It is 'other' . I am using `django 1.8` and also a `django-material` library. Will it be a problem ?

**Comment by mishbahr** [comment]
I've never used `django-material` before.  Can you try removing `material.admin` from `INSTALLED_APPS` and try using vanilla Django admin .. to see if the problem persists?

**Comment by Sahana312** [comment]
Yes I did try. Now it works. But I would want it with material. Do I have to put `'admin_reorder'` in any specific place so that it works?

**Comment by mishbahr** [comment]
I'm sorry but I don't know how `django-material` works... and I simply don't have the time to investigate.  `django-modeladmin-reorder` simply modifies/reorders view context via a middleware... maybe you can debug it by using django debug toolbar.  Good luck.
