### ISSUE TITLE
Admin "AUTHENTICATION AND AUTHORIZATION" replaced with a second set of my App and Tables in Admin

### ISSUE THREAD

**Issue by anacrust** [mishbahr/django-modeladmin-reorder#3]
Hello,

I added the modeladmin-reorder add-on and afterwards the Authentication and Authorization piece of http://localhost:8000/admin/ was replaced with a second set of my App (adaclients) and its model tables. I added the files to GitHub "https://github.com/anacrust/admin_reorder_issue". I can send/email you a screenshot if that helps.

Make sure in the GitHub code I posted the piece below isn't commented out.

MIDDLEWARE_CLASSES = [
 ... 
#'admin_reorder.middleware.ModelAdminReorder',
...
]

Thank you,
Matt

**Comment by mishbahr** [comment]
Looking at your `settings.py` in the project you've linked...

    ADMIN_REORDER = (
        'adaclients',
        {'app': 'adaclients','models':('adaclients.ParentCompany', 'adaclients.Company', 'adaclients.Account', 'adaclients.Trader')},
    )

You have defined `adaclients` twice? Is that your issue? Please refer to docs for proper sittings?

**Comment by anacrust** [comment]
Ty for your quick reply!

Per the docs, I'm simply trying to reorder

I revised to: 
```
ADMIN_REORDER = (
    # to remove 'adaclients',
    # Reorder app models
    {'app': 'adaclients','models': ('adaclients.ParentCompany', 'adaclients.Company', 'adaclients.Account', 'adaclients.Trader')},
)
```

The Authentication and Authorization piece is still missing. Now, I have only 1 App listed in with its tables(in my desired order) so no more duplication BUT Users and Groups are still missing. I did notice that if I don't include another app in the ADMIN_REORDER in settings.py, that App is not displayed as well. I'm not sure how the user section would be brought in with ADMIN_REORDER but seems like what I would have to do.

**Comment by mishbahr** [comment]
Just need to add `auth` to the `ADMIN_REORDER` setting

	ADMIN_REORDER = (
	    'auth',
	    'polls'
	    {
	    	'app': 'adaclients',
	    	'models': ('adaclients.ParentCompany', 'adaclients.Company', 'adaclients.Account', 'adaclients.Trader')
	    },
	    'sites',
	)

Looks like you've deleted your example repo. Hope the above snippet help. I'll close this for now.

Many Thanks

Mishbah
