### ISSUE TITLE
Keep admin.site.register models

### ISSUE THREAD

**Issue by LennyLip** [mishbahr/django-modeladmin-reorder#30]
Thanks for the application!

How we can keep showing admin.site.register models without listing it in ADMIN_REORDER?

For example, we have 
```
admin.site.register(app1.Model)
admin.site.register(app2.Model)
admin.site.register(app3.Model1)
admin.site.register(app3.Model2)

ADMIN_REORDER = (
       # Reorder app models
    {'app': 'app3', 'models': ('app3.Model1', 'app3.Model2')},
)
```

I want to show  app1.Model and app2.Model in admin too (without ordering), without select it in manual mode.

**Comment by mishbahr** [comment]
You can keep original label and models for any apps without reordering. 

You'll still have to explicitly include those apps.
```
ADMIN_REORDER = (
    'app1',
    'app2',
    # Reorder app3 models
    {'app': 'app3', 'models': ('app3.Model1', 'app3.Model2')},
)
```
