### ISSUE TITLE
missing built in apps in admin (cannot reference apps by app name/module)

### ISSUE THREAD

**Issue by peterlauri** [mishbahr/django-modeladmin-reorder#6]
We generate our ADMIN_REORDER setting like this:

```
ADMIN_EXCLUDE_APPS = ()

ADMIN_REORDER = (
    'designer',
)
ADMIN_REORDER += tuple(filter(lambda app: app not in ADMIN_EXCLUDE_APPS + ADMIN_REORDER, INSTALLED_APPS))
```

ADMIN_REORDER contains this after population (as expected)

```
('designer', 'modeltranslation', 'django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'django.contrib.sites', 'allauth', 'allauth.account', 'allauth.socialaccount', 'allauth.socialaccount.providers.google', 'allauth_invite', 'dolphin', 'bootstrapform', 'django_countries', 'django_tables2', 'django_filters', 'reversion', 'djcelery', 'kombu.transport.django', 'admin_reorder', 'django_slack', 'django_extensions', 'customer', 'subscriber', 'backoffice', 'debug_toolbar')
```

Visiting admin, only our own apps, and some third party apps (like djcelery) are displayed in the admin.

I checked the middleware, and it renames the apps using the label. Is that expected behavior? Shouldn't one be able to reference the app name as a module? Adding for example **auth** to the ADMIN_REORDER, makes **django.contrib.auth** pop up...

**Comment by mishbahr** [comment]
As we are manipulating context via a middleware, we don't have any control over the `app_label`. For nested apps such as `django.contrib.auth`, you'll have to use `auth` for `ADMIN_REORDER` setting. 

See https://github.com/django/django/blob/master/django/contrib/admin/sites.py#L384

`django-modeladmin-reorder` uses `app_label` to reorder things. Pull requests are welcome to support module names :-)

**Comment by mishbahr** [comment]
This is not really an issue. So I'll close this for now. Thanks
